name: Build and Release EXE

on:
  push:
    branches:
      - main   # 只在推到 main 時啟動

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --onefile --add-data output --add-data __pycache__ --add-data analysis_utils.py main.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
